### ISSUE TITLE
サーバーサイドで認証・認可をしていないので、自分がTwitterログインすらしていない状態でも誰かの作成済み年賀状を削除・改竄できる

### ISSUE THREAD

**Issue by kachick** [shuuuu10-01/rails-backend-newyearcard#1]
セキュリティ issue ですが、習作アプリだと思うので public にここで報告します。

再現手順
---

1. `curl 'https://rails-api-newyearcard.herokuapp.com//api/v1/cards/index'` で、全体の年賀状データを入手する
1. 任意のデータから `public_uid` を抜いてきて curl `https://rails-api-newyearcard.herokuapp.com//api/v1/cards/{public_uid}/destroy -XPOST` と打つ

(公開されている endpoint は https://github.com/shuuuu10-01/newyearmaker-backend/blob/367241491008bf2344cce34177d9d3b1b36be728/config/routes.rb#L1-L22 を見るとわかる)

そうすると、例えば以下のように既存データを消すことが出来ました。

<img width="1589" alt="スクリーンショット 2021-02-15 5 16 39" src="https://user-images.githubusercontent.com/1180335/107887975-33f82f00-6f4d-11eb-8e92-4384dc48ff1c.png">
<img width="1042" alt="スクリーンショット 2021-02-15 5 17 05" src="https://user-images.githubusercontent.com/1180335/107887978-378bb600-6f4d-11eb-854a-3f564a6cf893.png">

https://github.com/nizi24/PolPa-api/issues/21 や https://github.com/kuromitsu0104/gadget-app/issues/67 と同様の問題を抱えているのかな？と思いました。

**Comment by suu-u522** [comment]
ご指摘ありがとうございます。
セキュリティ面を何も考えていなかったので、このような状態のままになっていました。

早急に改善します。
