### ISSUE TITLE
固定値のACCESS_TOKEN がフロントエンドで公開されてしまっている為、任意の年賀状を削除できてしまう

### ISSUE THREAD

**Issue by kachick** [shuuuu10-01/rails-backend-newyearcard#3]
https://github.com/shuuuu10-01/newyearmaker-backend/issues/1 に対して https://github.com/shuuuu10-01/newyearmaker-backend/pull/2 や https://github.com/shuuuu10-01/newyearmaker-frontend/pull/1 といった改修をされたのかなと思うのですが、この ACCESS_TOKEN は固定値且つフロントエンドでは見えてしまう情報なのでそれ自体は対策になっていないかと思います。

この様に見えてしまう

<img width="695" alt="スクリーンショット 2021-02-19 2 40 15" src="https://user-images.githubusercontent.com/1180335/108400327-6dd37900-725e-11eb-9382-93a356fe60d7.png">

次に、 public_uid で年賀状情報を取得する

```sh
curl https://rails-api-newyearcard.herokuapp.com/api/v1/cards/c2ee49ae/show -H 'token:SDFfgsdSRE'
```

返ってきたレスポンスの中には uid が含まれている

```json
{"status":"SUCCESS","message":"Loaded the post","data":{"id":2,"uid":"1341559262095441920","text":"Sample01","gif":"card03","share":"0","created_at":"2020-12-31T07:46:02.513Z","updated_at":"2021-02-15T05:14:33.233Z","publ
ic_uid":"c2ee49ae","display_name":"NewYearGif","DM_id":"","top":null,"left":null,"width":null,"height":null,"select":false}}
```

これを使って、このようにリクエストを送る

```sh
curl https://rails-api-newyearcard.herokuapp.com/api/v1/cards/c2ee49ae/1341559262095441920/destroy -H 'token:SDFfgsdSRE' -X POST
```

そうすると、以下の様に自分はログインしていない状態で任意の年賀状を削除できてしまいました。

<img width="1121" alt="スクリーンショット 2021-02-19 2 43 02" src="https://user-images.githubusercontent.com/1180335/108400331-7035d300-725e-11eb-99fd-52feec0b55c2.png">
<img width="1166" alt="スクリーンショット 2021-02-19 2 54 58" src="https://user-images.githubusercontent.com/1180335/108400341-71670000-725e-11eb-9cdd-fa22f175c26c.png">

年賀状URLに public_uid が含まれている為、自分の年賀状を見て欲しいと公開すればその年賀状を誰でも認証不要で削除できるということになります。( 'https://rails-api-newyearcard.herokuapp.com//api/v1/cards/index' は削除されたようなので、前ほど第三者が入手しやすい情報というわけではありませんが......)
firebase 認証 & rails バックエンドという構成で似たような問題を抱えていらっしゃった https://github.com/nizi24/PolPa-api/issues/21#issuecomment-779154586 さんの対策が参考になるのでは？と思いました。以上、ご報告です。

**Comment by suu-u522** [comment]
ご指摘ありがとうございます。

参考になるページも合わせていただき、ありがとうございます。

**Comment by suu-u522** [comment]
対策として、前回追加したアクセストークンを用いた改修は無しにしました。

userテーブルを新しく追加し、そこにuidとフロントエンド側で取得したidトークンを保存するようにしました。
認可が必要なリクエストには、headersにidTokenを追加し、それがデータテーブルの値と一致する場合のみ実行するようにしました。

https://github.com/shuuuu10-01/newyearmaker-backend/blob/0ccff9d74908f93a5d859ea84244df2eab47e4d2/app/controllers/api/v2/cards_controller.rb#L52-L59

**Comment by kachick** [comment]
なるほど、僕も詳しくはないんですが、 firebase から発行される idToken って結構短時間で変わるものだった気がするんですが、そこは大丈夫ですかね？ (しばらく経って操作したら何も出来ない、とか起こりえるのかなと)

**Comment by suu-u522** [comment]
質問ありがとうございます。

今の改修において、idTokenを好きなように変えることができてしまうので、もう一度０から考え直します。

今後の改修として、
* フロント側でidTokenをfirebase受け取る
* idTokenをheadersに追加してAPI叩く
*  バックエンド側でidTokenを検証し、正しければ変更や削除を行う

ようにしたいと思います。

**Comment by kachick** [comment]
>バックエンド側でidTokenを検証し、正しければ変更や削除を行う

バックエンド側での検証stepは必要そうですよね、改修楽しみです👍

**Comment by suu-u522** [comment]
以下の部分の改修を行いました。
* バックエンド側でidTokenを検証し、正しければ変更や削除を行う

https://github.com/shuuuu10-01/newyearmaker-backend/blob/b10b154bbd1bf2306e32e75eee047190a81ec17c/app/controllers/api/v1/cards_controller.rb#L56-L72

**Comment by kachick** [comment]
良さそうですね、ありがとうございます！

**Comment by suu-u522** [comment]
issueありがとうございました。
フロントサイドがまだ残っていますので、引き続き行います。
